### ISSUE TITLE
Launch Exp. 2

### ISSUE THREAD

**Issue by hawkrobe** [hawkrobe/Q_and_A#9]
# To-do: 
* [x] Switch 'goal' to 'combo' (more concrete)
* [x] Make font size bigger for instructions at top (and maybe different color?)
* [x] Add indicator X/2 cards selected
* [x] include comprehension check at beginning walking through how they could reveal 2 cards for a single goal? 
* [x] don't allow questioner to send more than one question at once
* [x] make it clearer in instructions that answerer can reveal up to 2 cards (i.e. "try to reveal *all cards in goal set*")
* [x] change bonus mechanism such that you only get bonus if correct in first exchange (so no incentive to adopt cautious strategy)
* [x] print full "where is the..." question in chat window
* [x] implement private cue as to which goal is active
* [x] advance to next round once all needed cards have been revealed
* [x] fix weird bug where people disconnect (check for hidden tab timer that's not getting canceled for 2nd player...)
* [x] provide some indicator on answerer screen of which cards have already been revealed, e.g. by fading out (and don't let them click on them any more); also fade *in* for questioner
* [x] in `advanceRound` remove green border and disallow answerer to keep clicking cards (e.g. turn `messageSent` back off?
* [x] properly show chatbox when swapping roles
* [x]  put 'fog' in to make the 'hiddenness' more apparent?
* [x] call it 'possible goals'? And remove old goals before populating new ones
* [x] decide on bonus system
  * implement some incentive to get it done in as few rounds as possible?
  * subtract off from bonus for every card revealed?
* [x] decide how to restrict question typing
  * clever character limit?
  * just force the word "Where"?
* [x] decide on most diagnostic non-filler goal sets
  * overlapping? e.g. G1: [Ace of hearts, king of hearts], G2: [Ace of hearts, king of clubs]
* [x] BUG: baseline trials seem to not be enforcing that sets are non-overlapping (I got where they were perfect duplicates)
* [x] BUG: Show correct bonus calculation
* [x] don't allow negative bonus...
* [x] BUG: seems like selecting and unselecting still counts as additional 'selections' in bonus calculation?
* [x] write instructions
  * [x] make text bigger on instruction slide and shrink 2nd & 3rd images
  * [x] add in goal views to beginning
  * [x] emphasize bonus structure, i.e. that it's always possible to do it in a single exchange and this is how you get maximum bonus 
  * [x] make the survey question about "as soon as possible" clearer
  * [x] increase font size
  * [x] explain what green box means
* [x] If wait exceeds *five* minutes
* [x] check data written out in clean convention format
* [x] ensure each player sees each trial type in each role (i.e. so no one sees same trial type in same role)
* [x] haze seems to get displaced on completion?
* [x] seems to allow helper to select and send even while speaker is typing (i.e. I was just clicking on cards and hitting reveal, and then as soon as the message appeared, it instantly revealed the thing I had been clicking on)

# Setup

Inspired by multi-task RL designs, we have an agent (the seeker) who is trying to collect different sets of objects (specifically, cards) in an environment. Another player (the assistant) is trying to help. The seeker can ask questions, and the assistant can reveal information. Question-asking is motivated by the asymmetry in their knowledge: only the seeker knows which goal (i.e. which set) they're currently pursuing, and only the assistant knows the locations. 

In other words, we have a simplified, cooperative version of battleship. 

![image](https://user-images.githubusercontent.com/5262024/42915433-beb3cdfa-8ab4-11e8-9b2a-0c65d1fc468a.png)

# Implementation Details

* Possible goals (e.g. sets of cards the director could be trying to get) are shared in common ground, shown above map.

### Natural language version
* Repeat the following sequence for each goal set:
1. Questioner uses chat box for typing questions (same rules as Anselm et al battleship: no conjunctions, maybe a word limit, etc)
2. Answerer has chat box for typing answers (can type as much as they want, but maybe also a word limit?)
3. Questioner has a limited number of 'reveal' clicks on squares to find cards

### Restricted version
* Questioner has drop down menu containing choices of rank and suit to fill the blanks in "Where is the ___ of ____?"
* Answerer can click on cards to reveal them, at which point they enter the questioner's 'hand' 

# Conditions

* The trick is to pick goal sets that distinguish between our models and give rise to multi-round dialogue (ideally cases where sequence matters, i.e. answer to first question affects second question...)

**Comment by hawkrobe** [comment]
To-do: 
* [ ] implement private cue as to which goal is active
* [ ] advance to next round (with bonus) once all needed cards have been revealed
* [ ] provide some indicator on answerer screen of which cards have already been revealed, e.g. by fading out (and don't let them click on them any more)
* [ ] print full "where is the..." question in chat window
* [ ] implement some incentive to get it done in as few rounds as possible 
  * e.g. 
* [ ] implement non-filler goal sets (e.g. overlapping, or cards?)
